package(default_visibility = ["//visibility:public"])

cc_library(
    name = "image_encoding_lib",
    hdrs = ["image_encoding.h"],
    srcs = ["image_encoding.h", "image_encoding.cpp"],
    deps = ["@libavcodec//:shared_lib"]
)